# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0c33b4e064506f22ba829bb235657f09ba4903e2c18219e4f1b87eeb03cebb18cc7cc17525c2289ba701ddd33c8dce830e3ab6a7fc5903139cb7c0cdb0bdbc5

test:
  secret_key_base: b352f22f6e8dd461b03986a2d3db1f040d8fb94c809e5160fe164b141d69aad4d1f5e3bfdce6113da68b0cc90beb5bbec7201328ec4c99144ddd40cc7d2205d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
